<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:aop="http://www.springframework.org/schema/aop"
		xmlns:tx="http://www.springframework.org/schema/tx"
		xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.0.xsd
				http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-2.5.xsd
				http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-2.5.xsd">

	<!-- 修改过的配置 ：用于触发 AnnotationDrivenBeanDefinitionParser 的调试 -->
	<tx:annotation-driven proxy-target-class="false" order="0" />

	<aop:config>
		<!-- 修改过的配置 ：增加 order="1" -->
		<aop:advisor pointcut="execution(* *..ITestBean.*(..))" advice-ref="txAdvice" order="1" />
	</aop:config>

	<tx:advice id="txAdvice">
		<tx:attributes>
			<tx:method name="get*" read-only="true"/>
			<tx:method name="set*"/>
			<tx:method name="exceptional"/>
		</tx:attributes>
	</tx:advice>

	<tx:advice id="txRollbackAdvice">
		<tx:attributes>
			<tx:method name="get*" rollback-for="java.lang.Exception"/>
			<tx:method name="set*" no-rollback-for="java.lang.RuntimeException"/>
		</tx:attributes>
	</tx:advice>

	<bean id="transactionManager" class="org.springframework.tests.transaction.CallCountingTransactionManager"/>

	<bean id="testBean" class="org.springframework.tests.sample.beans.TestBean"/>

	<!-- 修改过的配置 ：增加 TestBean2 的声明  -->
	<bean id="testBean2" class="org.springframework.transaction.AmazarashiTestBean2" />

</beans>
